PierresTreats/Models/Treat.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
  public class Treat
  {
    public Treat()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int TreatId { get; set; }
    public string TreatName { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<FlavorTreat> JoinEntities { get; set; }
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;

namespace PierresTreats.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;

    public FlavorsController(PierresTreatsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;


namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat, int FlavorId)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisTreat = _db.Treats
          .Include(treat => treat.JoinEntities)
          .ThenInclude(join => join.Flavor)
          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Add a flavor</h2>

<h4>Add a flavor to this treat: @Html.DisplayFor(model => model.TreatName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to treats", "Index")</p>

PierresTreats/Views/Treats/Create.cshtml
@model PierresTreats.Models.Treat

@{
  Layout = "_Layout";
}

<h1>Add a Treat</h1>
<p>Add a Treat here:</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.TreatName)
  @Html.TextBoxFor(model => model.TreatName)

  <input type="submit" value="Add New Treat" />
}


<p><a href="/">Back home</a></p>
<p><a href="/treats">Back to treats.</a></p>

PierresTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.TreatName): @Html.DisplayFor(model => model.TreatName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to Treats", "Index")

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.TreatName): @Html.DisplayFor(model => model.TreatName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This Treat does not contain any flavors</p>
}
else
{
  <h4>Flavors the Treat contains:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{join.Flavor.FlavorName}", "Details", "Flavors", new { id = join.Flavor.FlavorId }, null)</li>
      @using (Html.BeginForm("DeleteFlavor", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete" />
      }
    }
  </ul>
}

<p>@Html.ActionLink("Back to treats", "Index")</p>
<p>@Html.ActionLink("Add a Flavor to this Treat", "AddFlavor", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.TreatName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.TreatName)
  @Html.EditorFor(model => model.TreatName)

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to treats", "Index")</p>

PierresTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
  <h3>No treats have been added yet!</h3>
}

@foreach (Treat treat in Model)
{
  <li>@Html.ActionLink($"{treat.TreatName}", "Details", new { id = treat.TreatId })</li>
}

<p>@Html.ActionLink("Add new treat", "Create")</p>
<p>@Html.ActionLink("Back to home", "Index", "Home")</p>